export const data = {
  accessories: [
    'Eyepatch.svg',
    'Glasses 2.svg',
    'Glasses 3.svg',
    'Glasses 4.svg',
    'Glasses 5.svg',
    'Glasses.svg',
    'Sunglasses 2.svg',
    'Sunglasses.svg',
    '_ None.svg'
  ],
  body: [
    'Blazer Black Tee.svg',
    'Button Shirt 1.svg',
    'Button Shirt 2.svg',
    'Coffee.svg',
    'Device.svg',
    'Dress.svg',
    'Explaining.svg',
    'Fur Jacket.svg',
    'Gaming.svg',
    'Gym Shirt.svg',
    'Hoodie.svg',
    'Killer.svg',
    'Macbook.svg',
    'Paper.svg',
    'Pointing Up.svg',
    'Polka Dot Jacket.svg',
    'Polo and Sweater.svg',
    'Shirt and Coat.svg',
    'Sporty Tee.svg',
    'Striped Pocket Tee.svg',
    'Striped Tee.svg',
    'Sweater Dots.svg',
    'Sweater.svg',
    'Tee 1.svg',
    'Tee 2.svg',
    'Tee Arms Crossed.svg',
    'Tee Selena.svg',
    'Thunder T-Shirt.svg',
    'Turtleneck.svg',
    'Whatever.svg'
  ],
  face: [
    'Angry with Fang.svg', 'Awe.svg',
    'Blank.svg',           'Calm.svg',
    'Cheeky.svg',          'Concerned Fear.svg',
    'Concerned.svg',       'Contempt.svg',
    'Cute.svg',            'Cyclops.svg',
    'Driven.svg',          'Eating Happy.svg',
    'Explaining.svg',      'Eyes Closed.svg',
    'Fear.svg',            'Hectic.svg',
    'Loving Grin 1.svg',   'Loving Grin 2.svg',
    'Monster.svg',         'Old.svg',
    'Rage.svg',            'Serious.svg',
    'Smile Big.svg',       'Smile LOL.svg',
    'Smile Teeth Gap.svg', 'Smile.svg',
    'Solemn.svg',          'Suspicious.svg',
    'Tired.svg',           'Very Angry.svg'
  ],
  facial_hair: [
    'Chin.svg',        'Full 2.svg',
    'Full 3.svg',      'Full 4.svg',
    'Full.svg',        'Goatee 1.svg',
    'Goatee 2.svg',    'Moustache 1.svg',
    'Moustache 2.svg', 'Moustache 3.svg',
    'Moustache 4.svg', 'Moustache 5.svg',
    'Moustache 6.svg', 'Moustache 7.svg',
    'Moustache 8.svg', 'Moustache 9.svg',
    '_ None.svg'
  ],
  head: [
    'Afro.svg',         'Bangs 2.svg',         'Bangs.svg',
    'Bantu Knots.svg',  'Bear.svg',            'Bun 2.svg',
    'Bun.svg',          'Buns.svg',            'Cornrows 2.svg',
    'Cornrows.svg',     'Flat Top Long.svg',   'Flat Top.svg',
    'Gray Bun.svg',     'Gray Medium.svg',     'Gray Short.svg',
    'hat-beanie.svg',   'hat-hip.svg',         'Hijab.svg',
    'Long Afro.svg',    'Long Bangs.svg',      'Long Curly.svg',
    'Long.svg',         'Medium 1.svg',        'Medium 2.svg',
    'Medium 3.svg',     'Medium Bangs 2.svg',  'Medium Bangs 3.svg',
    'Medium Bangs.svg', 'Medium Straight.svg', 'Mohawk 2.svg',
    'Mohawk.svg',       'No Hair 1.svg',       'No Hair 2.svg',
    'No Hair 3.svg',    'Pomp.svg',            'Shaved 1.svg',
    'Shaved 2.svg',     'Shaved 3.svg',        'Short 1.svg',
    'Short 2.svg',      'Short 3.svg',         'Short 4.svg',
    'Short 5.svg',      'Turban.svg',          'Twists 2.svg',
    'Twists.svg'
  ]
}